### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by promo-pr** [pistol88/yii2-gallery#1]
> Внимание! Христа ради, не забудьте добавить ['options' => ['enctype' => 'multipart/form-data']] для вашей формы.

[Tip](http://www.yiiframework.com/doc-2.0/guide-input-file-upload.html#rendering-file-input): since version 2.0.8, yii\web\widgets\ActiveField::fileInput adds enctype option to the form automatically when file input field is used.

**Comment by pistol88** [comment]
Update readme, thanks
